# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'Doubled'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}/kubernetes-manifests
    - name: Change K8s Manifest file
      run: sed -i '/livenessProbe/,+3 s/^/#/g' ${{ github.workspace }}/kubernetes-manifests/balance-reader.yaml
    - name: Change K8s Manifest file
      run: sed -i '/livenessProbe/,+3 s/^/#/g' ${{ github.workspace }}/kubernetes-manifests/transaction-history.yaml
    - name: Change K8s Manifest file
      run: sed -i '/livenessProbe/,+3 s/^/#/g' ${{ github.workspace }}/kubernetes-manifests/frontend.yaml
    - name: Append HPS to Balance Reader
      run: cat kubernetes-manifests/br-hpa.txt >> ${{ github.workspace }}/kubernetes-manifests/balance-reader.yaml
    - name: Apend HPA to Transaction History
      run: cat kubernetes-manifests/txn-hist-hpa.txt >> ${{ github.workspace }}/kubernetes-manifests/transaction-history.yaml

#     - name: Get Status
#       run: git add -A
#     - name: Get Status
#       run: git status

    # Commit and push the files back to the repo
    - name: Commit files  # transfer the new html files back into the repository
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'ddarwin'
        message: 'Updating Kubernetes Manifests'
        add: '["kubernetes-manifests/balance-reader.yaml","kubernetes-manifests/transaction-history.yaml","kubernetes-manifests/frontend.yaml"]'
